module.exports = {

   response :{
    recordset : [
        {
            "Empresa": "Makita",
            "TipoEntidad": "CLIENTE",
            "Entidad": "76279534-5",
            "Nombre": "MUSIL COMERCIAL SPA",
            "RazonSocial": "MUSIL COMERCIAL SPA",
            "CodLegal": "76279534-5",
            "Vigencia": "S",
            "Direccion": "SANTA ROSA 1508-1510",
            "Comuna": "SANTIAGO",
            "Ciudad": "SANTIAGO",
            "Fono": "24500018",
            "Fax": "",
            "eMail": "serviciossantarosa@123.cl",
            "Giro": "SERVICIO TECNICO",
            "Banco": "",
            "CuentaBanco": "",
            "Moneda": "",
            "Ejecutivo": "IMIRANDA",
            "MontoCredito": 15440000,
            "FechaCredito": "1900-01-01T00:00:00.000Z",
            "PlazoCredito": 3,
            "CuentaResultado": "",
            "CuentaBalance": "",
            "CuentaCompra": "",
            "CuentaVenta": "",
            "CuentaAjuste": "",
            "Categoria": "SERVICIO TECNICO",
            "Zona": "13 REGION",
            "Sector": "CL",
            "DireccionLegal": "SANTA ROSA 1508-1510",
            "ComunaLegal": "SANTIAGO",
            "CiudadLegal": "SANTIAGO",
            "Actividad": 0,
            "Sucursal": "",
            "SucursalSII": 0,
            "DirPostal": "",
            "Contacto": "LUIS MUÑOZ",
            "RepresentanteLegal": "",
            "CodLegalRepresentante": "",
            "CondPago": "60 DÍAS",
            "ListaPrecio": "UNICA",
            "Clasif1": "STA",
            "Clasif2": "LCOÑOMAN",
            "Clasif3": null,
            "Clasif4": null,
            "Clasif5": null,
            "Clasif6": null,
            "Clasif7": null,
            "Clasif8": null,
            "Clasif9": null,
            "Clasif10": null,
            "Clasif11": null,
            "Clasif12": null,
            "Clasif13": null,
            "Clasif14": null,
            "Clasif15": null,
            "Clasif16": null,
            "Clasif17": null,
            "Clasif18": null,
            "Clasif19": null,
            "Clasif20": null,
            "Texto1": "",
            "Texto2": "I",
            "Texto3": "",
            "Texto4": "",
            "Texto5": "serviciossantarosa@123.cl",
            "Valor1": 0,
            "Valor2": 0,
            "Valor3": 0,
            "Valor4": 0,
            "Valor5": 0,
            "Fecha1": "2018-07-27T00:00:00.000Z",
            "Fecha2": null,
            "Fecha3": null,
            "Fecha4": null,
            "Fecha5": null,
            "Logico1": "S",
            "Logico2": "S",
            "Observaciones": "19-01-2023 REEVALUCION DE AUMENTO DE LINEA DE CRÉDITO EN DIC.2022- SE RECHAZA AUMENTO POR \r\nPB PD AD EP LA. CGIL\r\nactualizacion LC 400 $35.600 PV 11.04\r\nactualizacion LC 400 $36.700 PV 01.02.24\r\n06/05/24  ACTUALIZACIÓN VALOR UF $38.600//C.F",
            "FechaModif": "2024-05-06T15:38:28.817Z",
            "UsuarioModif": "CFERRADA",
            "FormaPago": "",
            "Imagen": "",
            "FechaNacimiento": "1900-01-01T00:00:00.000Z",
            "Sexo": "",
            "EstadoCivil": "",
            "FechaDesde": "1900-01-01T00:00:00.000Z",
            "FechaHasta": "1900-01-01T00:00:00.000Z",
            "CausaTermino": "",
            "TipoContrato": "",
            "TDSueldo": "",
            "TDAnticipo": "",
            "TDRentaAccesoria": "",
            "TDFiniquito": "",
            "TDOtro": "",
            "SueldoBase": 0,
            "HorasSemana": 0,
            "Calendario": null,
            "Area": "",
            "CentroCosto": "",
            "Cargo": "",
            "Valor6": 0,
            "Valor7": 0,
            "Valor8": 0,
            "Valor9": 0,
            "Valor10": 0,
            "Fecha6": null,
            "Fecha7": null,
            "Fecha8": null,
            "Fecha9": null,
            "Fecha10": null
        }
    ]

   }
   
};